import { okResult } from "../io/output";
import { type CliContext, type CliResult } from "../runtime/command-types";
import { CLI_VERSION } from "../runtime/version";

const ROOT_HELP = [
  "Trekoon - AI-first local issue tracker",
  `Version: ${CLI_VERSION}`,
  "",
  "Usage:",
  "  trekoon [global-options] <command> [command-options]",
  "",
  "Global options:",
  "  --json       Structured JSON output",
  "  --toon       TOON-encoded output (preferred for agents)",
  "  --compat <mode>  Machine compatibility mode",
  "  --help       Show help for root or a command",
  "  --version    Print CLI version",
  "",
  "Commands:",
  "  help         Show help for root or a command",
  "  init         Create or re-bootstrap .trekoon storage",
  "  quickstart   Storage model, agent loop, and common patterns",
  "  wipe         Delete repo-wide .trekoon state (requires --yes)",
  "  board        Open or update the local board",
  "  epic         Create, list, update, search, and track epics",
  "  task         Create, list, update, search, and complete tasks",
  "  subtask      Create, list, update, and search subtasks",
  "  dep          Manage dependency edges between tasks and subtasks",
  "  events       Prune old sync event log rows",
  "  migrate      Check schema version or roll back migrations",
  "  session      Agent orientation (diagnostics + sync + next task)",
  "  suggest      Priority-ranked next-action suggestions",
  "  sync         Pull events and resolve conflicts across branches",
  "  skills       Install, link, or update the Trekoon skill",
  "  update       Alias for skills update",
].join("\n");

const INIT_HELP = [
  "Usage: trekoon init [--json|--toon]",
  "",
  "Creates or re-bootstraps the repo-scoped .trekoon directory and database.",
  "In worktree setups, every worktree shares the same DB.",
  "",
  "Keep .trekoon gitignored. Committing the SQLite DB is not a recovery path.",
  "",
  "Examples:",
  "  trekoon init",
  "  trekoon --json init",
].join("\n");

const QUICKSTART_HELP = [
  "Usage: trekoon quickstart [--json|--toon]",
  "",
  "Prints the storage model, agent execution loop, and common command patterns.",
  "",
  "Recommended startup flow:",
  "  1. trekoon --toon session",
  "  2. Stop if diagnostics report recoveryRequired or a tracked/ignored mismatch",
  "  3. If behind: trekoon --toon sync pull --from main",
  "  4. Claim work: trekoon --toon task update <task-id> --status in_progress",
  "  5. Finish: trekoon --toon task done <task-id>",
  "",
  "Manual bootstrap (if you need step-by-step):",
  "  1. trekoon --toon init",
  "  2. trekoon --toon sync status",
  "  3. trekoon --toon task next",
  "",
  "Examples:",
  "  trekoon quickstart",
  "  trekoon --toon quickstart",
].join("\n");

const WIPE_HELP = [
  "Usage: trekoon wipe --yes [--json|--toon]",
  "",
  "Deletes the shared .trekoon directory for the entire repository.",
  "In worktree setups, this erases state for every linked worktree.",
  "",
  "Options:",
  "  --yes  Required. Confirms you want the destructive delete.",
  "",
  "This is a last-resort recovery tool. Don't use it to fix gitignore",
  "issues or replace proper bootstrap diagnostics.",
  "",
  "Examples:",
  "  trekoon wipe --yes",
].join("\n");

const BOARD_HELP = [
  "Usage: trekoon board <open|update>",
  "",
  "Subcommands:",
  "  open    Install board assets, start a local server on 127.0.0.1,",
  "          and open the browser. Returns the board URL and a fallback URL.",
  "  update  Refresh board runtime assets only. No server, no browser.",
  "",
  "Environment:",
  "  TREKOON_BOARD_ASSET_ROOT  Override the bundled asset source (tests/dev only).",
  "",
  "Examples:",
  "  trekoon board open",
  "  trekoon --json board update",
].join("\n");

const EPIC_HELP = [
  "Usage: trekoon epic <create|expand|list|show|search|replace|update|delete|progress> [options]",
  "",
  "Create:",
  "  trekoon epic create --title \"...\" --description \"...\" [--status <status>]",
  "  trekoon epic create --title \"...\" --description \"...\" [--task <spec>] [--subtask <spec>] [--dep <spec>]",
  "  When the full tree is known, the second form creates everything in one shot",
  "  and returns mappings/counts. Same compact spec grammar as epic expand.",
  "",
  "Expand:",
  "  trekoon epic expand <epic-id> [--task <spec>] [--subtask <spec>] [--dep <spec>]",
  "  --task <temp-key>|<title>|<description>|<status>",
  `  --subtask <parent-ref>|<temp-key>|<title>|<description>|<status>  (${"@"}<temp-key> for new parents)`,
  `  --dep <source-ref>|<depends-on-ref>  (refs can be IDs or ${"@"}<temp-key>)`,
  "  Escapes in compact specs: \\| for |, \\\\ for \\, \\n, \\r, \\t",
  "",
  "List:",
  "  Defaults: open work only (in_progress, todo), limit 10.",
  "  --status <csv> | --limit <n> | --cursor <n> | --all | --view table|compact",
  "  Pagination: --cursor is offset-like. Machine output has meta.pagination.hasMore / nextCursor.",
  "  --all is mutually exclusive with --status, --limit, and --cursor.",
  "",
  "Show:",
  "  --view table (default) | compact | tree | detail",
  "  With --all in machine mode, defaults to detail view.",
  "",
  "Search/Replace:",
  "  trekoon epic search <epic-id> \"search text\" [--fields title|description|title,description] [--preview]",
  "  Searches epic + descendant task/subtask titles and descriptions.",
  "",
  "  trekoon epic replace <epic-id> --search \"text\" --replace \"text\" [--apply]",
  "  Preview is default. Use --apply to write changes. --preview and --apply are mutually exclusive.",
  "",
  "Update (bulk mode, no positional ID):",
  "  trekoon epic update --all --append <text> [--status <status>]",
  "  trekoon epic update --ids <csv> --append <text> [--status <status>]",
  "  Per-row updates, not one atomic transaction.",
  "",
  "Update (cascade mode, with positional ID):",
  "  trekoon epic update <epic-id> --all --status done|todo",
  "  Cascades atomically through all descendant tasks and subtasks.",
  "  Blocked descendants abort the whole update. Only --status done|todo is supported.",
  "  Don't combine positional ID + --all with --ids, --append, --description, or --title.",
  "",
  "Progress:",
  "  trekoon epic progress <epic-id>",
  "  Returns done/in_progress/blocked/todo counts, readyCount, and nextCandidate.",
].join("\n");

const TASK_HELP = [
  "Usage: trekoon task <create|create-many|list|show|ready|next|done|search|replace|update|delete> [options]",
  "",
  "Create-many:",
  "  trekoon task create-many --epic <epic-id> --task <spec> [--task <spec> ...]",
  "  --task <temp-key>|<title>|<description>|<status>",
  "  Multiple --task flags are applied in order.",
  "  Escapes in compact specs: \\| for |, \\\\ for \\, \\n, \\r, \\t",
  "",
  "List:",
  "  Defaults: open work only (in_progress, todo), limit 10.",
  "  --epic <id> | --status <csv> | --limit <n> | --cursor <n> | --all | --view table|compact",
  "  Pagination: --cursor is offset-like. Machine output has meta.pagination.hasMore / nextCursor.",
  "  --all is mutually exclusive with --status, --limit, and --cursor.",
  "",
  "Show:",
  "  --view table (default) | compact | tree | detail",
  "  With --all in machine mode, defaults to detail view.",
  "",
  "Ready/Next:",
  "  ready  Returns unblocked candidates sorted by status, blockers, createdAt, id.",
  "         Options: --limit <n>, --epic <id>",
  "  next   Returns the top ready candidate. Option: --epic <id>",
  "",
  "Done:",
  "  trekoon task done <task-id>",
  "  Marks the task complete, auto-transitions through in_progress if needed,",
  "  reports unblocked downstream tasks, warns about open subtasks, and returns",
  "  the next ready candidate.",
  "",
  "Search/Replace:",
  "  trekoon task search <task-id> \"search text\" [--fields title|description|title,description] [--preview]",
  "  Searches task + descendant subtask titles and descriptions.",
  "",
  "  trekoon task replace <task-id> --search \"text\" --replace \"text\" [--apply]",
  "  Preview is default. Use --apply to write changes. --preview and --apply are mutually exclusive.",
  "",
  "Update (bulk mode, no positional ID):",
  "  trekoon task update --all --append <text> [--status <status>]",
  "  trekoon task update --ids <csv> --append <text> [--status <status>]",
  "  Per-row updates, not one atomic transaction.",
  "",
  "Update (cascade mode, with positional ID):",
  "  trekoon task update <task-id> --all --status done|todo",
  "  Cascades atomically through descendant subtasks.",
  "  Blocked descendants abort the whole update. Only --status done|todo is supported.",
  "  Don't combine positional ID + --all with --ids, --append, --description, or --title.",
].join("\n");

const SUBTASK_HELP = [
  "Usage: trekoon subtask <create|create-many|list|search|replace|update|delete> [options]",
  "",
  "Create-many:",
  "  trekoon subtask create-many [<task-id>] [--task <task-id>] --subtask <spec> [--subtask <spec> ...]",
  "  --subtask <temp-key>|<title>|<description>|<status>",
  "  Positional <task-id> and --task can be combined only when equal.",
  "  Multiple --subtask flags are applied in order.",
  "  Escapes in compact specs: \\| for |, \\\\ for \\, \\n, \\r, \\t",
  "",
  "List:",
  "  Defaults: open work only (in_progress, todo), limit 10.",
  "  --task <id> | --status <csv> | --limit <n> | --cursor <n> | --all | --view table|compact",
  "  Pagination: --cursor is offset-like. Machine output has meta.pagination.hasMore / nextCursor.",
  "  --all is mutually exclusive with --status, --limit, and --cursor.",
  "",
  "Search/Replace:",
  "  trekoon subtask search <subtask-id> \"search text\" [--fields title|description|title,description] [--preview]",
  "  Searches subtask title and description only.",
  "",
  "  trekoon subtask replace <subtask-id> --search \"text\" --replace \"text\" [--apply]",
  "  Preview is default. Use --apply to write changes. --preview and --apply are mutually exclusive.",
  "",
  "Update (bulk mode, no positional ID):",
  "  trekoon subtask update --all --append <text> [--status <status>]",
  "  trekoon subtask update --ids <csv> --append <text> [--status <status>]",
  "  Per-row updates, not one atomic transaction.",
  "",
  "Update (positional-ID cascade syntax):",
  "  trekoon subtask update <subtask-id> --all --status done|todo",
  "  Accepted for consistency, but just updates the one subtask (no descendants).",
  "  Don't combine positional ID + --all with --ids, --append, --description, or --title.",
].join("\n");

const DEP_HELP = [
  "Usage: trekoon dep <add|add-many|remove|list|reverse> [options]",
  "",
  "Subcommands:",
  "  add <source-id> <depends-on-id>",
  "      Create a dependency edge: source depends on depends-on.",
  "  add-many --dep <source-ref>|<depends-on-ref> [--dep <spec> ...]",
  "      Create multiple edges from compact specs in order.",
  "      Uses persisted IDs only; @<temp-key> refs are for batch workflows.",
  "  remove <source-id> <depends-on-id>",
  "      Remove one dependency edge.",
  "  list <source-id>",
  "      Show direct dependencies for a node.",
  "  reverse <target-id>",
  "      Show downstream nodes blocked by target (with distance).",
  "",
  "Examples:",
  "  trekoon dep add <task-a> <task-b>",
  "  trekoon dep remove <task-a> <task-b>",
  "  trekoon dep list <task-a>",
  "  trekoon dep reverse <task-b>",
].join("\n");

const EVENTS_HELP = [
  "Usage: trekoon events prune [--dry-run] [--archive] [--retention-days <n>]",
  "",
  "Cleans up old sync event log rows.",
  "",
  "Options:",
  "  --dry-run             Preview counts only, don't delete anything.",
  "  --archive             Copy pruned rows to event_archive before deleting.",
  "  --retention-days <n>  Keep the last n days (positive integer, default 90).",
  "",
  "Examples:",
  "  trekoon events prune --dry-run",
  "  trekoon events prune --retention-days 30",
  "  trekoon events prune --archive",
].join("\n");

const MIGRATE_HELP = [
  "Usage: trekoon migrate <status|rollback> [--to-version <n>]",
  "",
  "Subcommands:",
  "  status                Show current schema version, latest version, and pending count.",
  "  rollback [--to-version <n>]  Roll back migrations. Defaults to one version back.",
  "",
  "Examples:",
  "  trekoon migrate status",
  "  trekoon migrate rollback",
  "  trekoon migrate rollback --to-version 1",
].join("\n");

const SYNC_HELP = [
  "Usage: trekoon sync <status|pull|resolve|conflicts> [options]",
  "",
  "Subcommands:",
  "  status [--from <branch>]",
  "      Ahead/behind counts and pending conflicts vs a source branch (default: main).",
  "  pull --from <branch>",
  "      Pull upstream tracker events from a source branch.",
  "  conflicts list [--mode pending|all]",
  "      List sync conflicts (default: pending only).",
  "  conflicts show <conflict-id>",
  "      Show full details for one conflict.",
  "  resolve <conflict-id> --use ours|theirs [--dry-run]",
  "      Resolve a conflict. --dry-run previews without writing.",
  "  resolve --all --use ours|theirs [--entity <id>] [--field <name>] [--dry-run]",
  "      Batch-resolve all pending conflicts matching filters.",
  "",
  "Ours vs theirs:",
  "  Conflicts are field-level (e.g., status, title, description on one entity).",
  "  --use ours   Keep the current DB value. Nothing is written.",
  "  --use theirs  Overwrite the DB field with the source-branch value.",
  "",
  "  Example: epic abc123, field: status",
  "    ours (current DB): in_progress",
  "    theirs (source branch): done",
  "    --use ours  -> stays in_progress",
  "    --use theirs -> becomes done",
  "",
  "Compatibility:",
  "  --compat legacy-sync-command-ids",
  "      Emits legacy sync command IDs (sync_status, sync_pull, ...) in machine",
  "      output. Includes deprecation metadata. Window closes after 2026-09-30.",
  "      Migration: drop --compat and use dotted IDs (sync.status).",
  "",
  "Examples:",
  "  trekoon sync status",
  "  trekoon sync status --from main",
  "  trekoon sync pull --from main",
  "  trekoon sync conflicts list",
  "  trekoon sync conflicts list --mode all",
  "  trekoon sync conflicts show <conflict-id>",
  "  trekoon sync resolve <conflict-id> --use ours",
  "  trekoon sync resolve --all --use ours",
  "  trekoon sync resolve --all --use ours --field status",
  "  trekoon sync resolve --all --use ours --entity <id> --dry-run",
].join("\n");

const SESSION_HELP = [
  "Usage: trekoon session [--epic <epic-id>] [--json|--toon]",
  "",
  "One-call agent orientation. Opens the DB once and returns:",
  "  - diagnostics: storageMode, recoveryRequired, recoveryStatus",
  "  - sync: ahead/behind counts and pendingConflicts vs main",
  "  - next: full task tree with subtasks for the top ready candidate (null if none)",
  "  - nextDeps: blocker list with statuses (empty if none)",
  "  - readiness: readyCount and blockedCount across all open tasks",
  "",
  "Options:",
  "  --epic <epic-id>  Scope readiness to a specific epic.",
  "",
  "Output modes:",
  "  human  Multi-section summary (default in TTY)",
  "  toon   Compact pipe-encoded envelope",
  "  json   Full structured JSON envelope",
  "",
  "Examples:",
  "  trekoon session",
  "  trekoon --toon session",
  "  trekoon --toon session --epic <epic-id>",
  "  trekoon --json session",
].join("\n");

const SUGGEST_HELP = [
  "Usage: trekoon suggest [--epic <epic-id>] [--json|--toon]",
  "",
  "Returns up to 3 priority-ranked next-action suggestions based on recovery",
  "state, sync status, task readiness, and epic progress.",
  "",
  "Options:",
  "  --epic <epic-id>  Scope suggestions to a specific epic.",
  "",
  "Categories:",
  "  recovery   Storage needs repair",
  "  sync       Behind main or pending conflicts",
  "  execution  In-progress or ready tasks to pick up",
  "  planning   All blocked, epic close, or empty tracker",
  "",
  "Each suggestion includes an action, a ready-to-run command, and a reason.",
  "",
  "Examples:",
  "  trekoon suggest",
  "  trekoon --toon suggest",
  "  trekoon --toon suggest --epic <epic-id>",
].join("\n");

const SKILLS_HELP = [
  "Usage:",
  "  trekoon skills install [--link --editor opencode|claude|pi] [--to <path>] [--allow-outside-repo]",
  "  trekoon skills install -g|--global [--editor opencode|claude|pi]",
  "  trekoon skills update",
  "",
  "Installs or refreshes the Trekoon skill so AI agents can plan and execute.",
  "",
  "Local install (default):",
  "  Creates a symlink at .agents/skills/trekoon pointing to the bundled source,",
  "  so the skill always matches the installed CLI version.",
  "  --link            Also create an editor symlink named 'trekoon'.",
  "  --editor <name>   Required with --link (opencode|claude|pi).",
  "  --to <path>       Override the symlink root for --link only.",
  "  --allow-outside-repo  Allow links outside the repo (requires --link).",
  "",
  "Global install (-g|--global):",
  "  Creates a global symlink at ~/.agents/skills/trekoon and per-editor symlinks",
  "  under each editor's global skills directory.",
  "  --editor <name>   Install for a single editor only.",
  "",
  "Update:",
  "  Probes and repairs both global and local symlinks.",
  "  Reports per-entry status: ok, repointed, created, migrated, skipped.",
  "",
  "Alias: trekoon update -> trekoon skills update",
  "",
  "Examples:",
  "  trekoon skills install",
  "  trekoon skills install -g",
  "  trekoon skills install --global --editor claude",
  "  trekoon skills install --link --editor opencode",
  "  trekoon skills install --link --editor claude --to .claude/skills",
  "  trekoon skills install --link --editor pi --to ../shared/skills --allow-outside-repo",
  "  trekoon skills update",
  "  trekoon update",
].join("\n");

const COMMAND_HELP: Record<string, string> = {
  init: INIT_HELP,
  board: BOARD_HELP,
  quickstart: QUICKSTART_HELP,
  session: SESSION_HELP,
  wipe: WIPE_HELP,
  epic: EPIC_HELP,
  task: TASK_HELP,
  subtask: SUBTASK_HELP,
  dep: DEP_HELP,
  events: EVENTS_HELP,
  migrate: MIGRATE_HELP,
  sync: SYNC_HELP,
  suggest: SUGGEST_HELP,
  skills: SKILLS_HELP,
  update: "Usage: trekoon update [--json|--toon]\n\nAlias for: trekoon skills update\n\nProbes and repairs all installed global and local skill symlinks.",
  help: "Usage: trekoon help [command] [--json|--toon]",
};

export function resolveHelpText(topic: string | null): string {
  if (!topic) {
    return ROOT_HELP;
  }

  return COMMAND_HELP[topic] ?? `Unknown command for help: ${topic}`;
}

export async function runHelp(context: CliContext): Promise<CliResult> {
  const topic: string | null = context.args[0] ?? null;
  const text: string = resolveHelpText(topic);

  return okResult({
    command: "help",
    human: text,
    data: {
      topic,
      text,
      version: CLI_VERSION,
    },
  });
}
