import { okResult } from "../io/output";
import { type CliContext, type CliResult } from "../runtime/command-types";
import { CLI_VERSION } from "../runtime/version";

const ROOT_HELP = [
  "Trekoon - AI-first local issue tracker",
  `Version: ${CLI_VERSION}`,
  "",
  "Usage:",
  "  trekoon [global-options] <command> [command-options]",
  "",
  "Global options:",
  "  --json       Emit stable JSON machine output",
  "  --toon       Emit true TOON-encoded output",
  "  --compat <mode>  Enable explicit machine compatibility mode",
  "  --help       Show root or command help",
  "  --version    Print CLI version",
  "",
  "Commands:",
  "  help         Show root or command help",
  "  init         Initialize repo-shared .trekoon storage and DB",
  "  quickstart   Show shared-storage bootstrap + AI execution loop",
  "  wipe         Remove repo-shared Trekoon state (requires --yes)",
  "  board        Local board asset and browser commands",
  "  epic         Epic lifecycle commands",
  "  task         Task lifecycle commands",
  "  subtask      Subtask lifecycle commands",
  "  dep          Dependency graph commands",
  "  events       Event retention and cleanup commands",
  "  migrate      Migration status and rollback commands",
  "  session      One-call agent orientation (diagnostics + sync + next task)",
  "  sync         Cross-branch sync commands",
  "  skills       Project-local skill install/update/link",
].join("\n");

const INIT_HELP = [
  "Usage: trekoon init [--json|--toon]",
  "",
  "Purpose:",
  "  Initialize repo-scoped Trekoon storage (.trekoon) and database.",
  "  In git worktrees, every worktree shares the same repository DB.",
  "  Keep .trekoon gitignored; committing the SQLite DB is not a recovery path.",
  "",
  "Examples:",
  "  trekoon init",
  "  trekoon --json init",
].join("\n");

const QUICKSTART_HELP = [
  "Usage: trekoon quickstart [--json|--toon]",
  "",
  "Purpose:",
  "  Show shared-storage bootstrap, diagnostics, and the canonical AI loop.",
  "",
  "Flow:",
  "  1) trekoon --toon init",
  "  2) trekoon --toon sync status",
  "  3) Fail fast on recoveryRequired or tracked/ignored mismatch diagnostics",
  "  4) trekoon --toon task ready --limit 5",
  "  5) trekoon --toon task next",
  "  6) trekoon --toon dep reverse <task-or-subtask-id>",
  "  7) trekoon --toon task update <task-id> --status in_progress",
  "",
  "Examples:",
  "  trekoon quickstart",
  "  trekoon --toon quickstart",
].join("\n");

const WIPE_HELP = [
  "Usage: trekoon wipe --yes [--json|--toon]",
  "",
  "Purpose:",
  "  Remove the repository's shared Trekoon storage directory.",
  "  In git worktrees this erases the same .trekoon state for every linked worktree.",
  "",
  "Options:",
  "  --yes  Required confirmation for destructive repo-wide removal.",
  "",
  "Recovery guidance:",
  "  Use wipe only for explicit destructive recovery.",
  "  Do not use wipe to fix gitignore mistakes or to replace bootstrap diagnostics.",
  "",
  "Examples:",
  "  trekoon wipe --yes",
].join("\n");

const BOARD_HELP = [
  "Usage: trekoon board <open|update>",
  "",
  "Subcommands:",
  "  open",
  "      Ensure board assets are installed, start a 127.0.0.1 board server,",
  "      and launch the browser. Machine output includes server URL, fallback URL,",
  "      and launch metadata.",
  "  update",
  "      Refresh board runtime assets only. Does not start the server or open a browser.",
  "",
  "Environment overrides:",
  "  TREKOON_BOARD_ASSET_ROOT  Optional asset source override for tests and local development.",
  "",
  "Examples:",
  "  trekoon board open",
  "  trekoon --json board update",
].join("\n");

const EPIC_HELP = [
  "Usage: trekoon epic <create|expand|list|show|search|replace|update|delete> [options]",
  "",
  "Create behavior:",
  "  trekoon epic create --title \"...\" --description \"...\" [--status <status>]",
  "  trekoon epic create --title \"...\" --description \"...\" [--task <spec>] [--subtask <spec>] [--dep <spec>]",
  "  Preferred one-shot flow when the full tree is known up front.",
  "  Uses the same compact spec grammar as epic expand and returns mappings/counts.",
  "",
  "Expand behavior:",
  "  trekoon epic expand <epic-id> [--task <spec>] [--subtask <spec>] [--dep <spec>]",
  "  --task <temp-key>|<title>|<description>|<status>",
  `  --subtask <parent-ref>|<temp-key>|<title>|<description>|<status>  (use ${"@"}<temp-key> for newly declared parents)`,
  `  --dep <source-ref>|<depends-on-ref>  (refs can be ids or ${"@"}<temp-key>)`,
  "  Escapes inside compact specs: \\| for |, \\\\ for \\, \\n, \\r, \\t",
  "",
  "List behavior:",
  "  Defaults:",
  "    - Open statuses only: in_progress, in-progress, todo",
  "    - Limit: 10",
  "  Flags:",
  "    --status <csv> | --limit <n> | --cursor <n> | --all | --view table|compact",
  "  Pagination:",
  "    - --cursor is offset-like",
  "    - Machine modes expose meta.pagination.hasMore / nextCursor",
  "  Constraints:",
  "    - --all is mutually exclusive with --status, --limit, and --cursor",
  "",
  "Show behavior:",
  "  Views:",
  "    - table: default view",
  "    - compact: epic summary",
  "    - tree: hierarchy",
  "    - detail: descriptions",
  "  Machine default:",
  "    - With --all, machine modes default to detail",
  "",
  "Search/Replace behavior:",
  "  search:",
  "    - trekoon epic search <epic-id> \"search text\"",
  "    - Options: --fields title|description|title,description, --preview",
  "    - Scope: epic title/description + descendant task/subtask title/description",
  "  replace:",
  "    - trekoon epic replace <epic-id> --search \"text\" --replace \"text\"",
  "    - Preview is default; use --apply to mutate",
  "    - --preview and --apply are mutually exclusive",
  "",
  "Update behavior:",
  "  Repo-wide bulk mode:",
  "    trekoon epic update --all --append <text> [--status <status>]",
  "    trekoon epic update --ids <csv> --append <text> [--status <status>]",
  "    - preserves existing per-row bulk behavior; not one atomic multi-row update",
  "  Descendant cascade mode:",
  "    trekoon epic update <epic-id> --all --status done|todo",
  "    - cascades atomically through descendant tasks and subtasks",
  "    - blocked descendants abort the whole update",
  "    - cascade mode supports only --status done|todo",
  "    - do not combine positional id + --all with --ids, --append, --description, or --title",
].join("\n");

const TASK_HELP = [
  "Usage: trekoon task <create|create-many|list|show|ready|next|done|search|replace|update|delete> [options]",
  "",
  "Create-many behavior:",
  "  trekoon task create-many --epic <epic-id> --task <spec> [--task <spec> ...]",
  "  --task <temp-key>|<title>|<description>|<status>",
  "  Rejects unexpected positional arguments and empty required fields.",
  "  Repeated --task flags are applied in the order provided.",
  "  Escapes inside compact specs: \\| for |, \\\\ for \\, \\n, \\r, \\t",
  "",
  "List behavior:",
  "  Defaults:",
  "    - Open statuses only: in_progress, in-progress, todo",
  "    - Limit: 10",
  "  Flags:",
  "    --epic <id> | --status <csv> | --limit <n> | --cursor <n> | --all | --view table|compact",
  "  Pagination:",
  "    - --cursor is offset-like",
  "    - Machine modes expose meta.pagination.hasMore / nextCursor",
  "  Constraints:",
  "    - --all is mutually exclusive with --status, --limit, and --cursor",
  "",
  "Show behavior:",
  "  Views:",
  "    - table: default view",
  "    - compact: task summary",
  "    - tree: hierarchy",
  "    - detail: descriptions",
  "  Machine default:",
  "    - With --all, machine modes default to detail",
  "",
  "Ready/Next behavior:",
  "  ready:",
  "    - Returns deterministic unblocked candidates",
  "    - Sort order: status, blockers, createdAt, id",
  "    - Options: --limit <n>, --epic <id>",
  "  next:",
  "    - Returns top ready candidate",
  "    - Option: --epic <id>",
  "",
  "Search/Replace behavior:",
  "  search:",
  "    - trekoon task search <task-id> \"search text\"",
  "    - Options: --fields title|description|title,description, --preview",
  "    - Scope: task title/description + descendant subtask title/description",
  "  replace:",
  "    - trekoon task replace <task-id> --search \"text\" --replace \"text\"",
  "    - Preview is default; use --apply to mutate",
  "    - --preview and --apply are mutually exclusive",
  "",
  "Update behavior:",
  "  Repo-wide bulk mode:",
  "    trekoon task update --all --append <text> [--status <status>]",
  "    trekoon task update --ids <csv> --append <text> [--status <status>]",
  "    - preserves existing per-row bulk behavior; not one atomic multi-row update",
  "  Descendant cascade mode:",
  "    trekoon task update <task-id> --all --status done|todo",
  "    - cascades atomically through descendant subtasks",
  "    - blocked descendants abort the whole update",
  "    - cascade mode supports only --status done|todo",
  "    - do not combine positional id + --all with --ids, --append, --description, or --title",
].join("\n");

const SUBTASK_HELP = [
  "Usage: trekoon subtask <create|create-many|list|search|replace|update|delete> [options]",
  "",
  "Create-many behavior:",
  "  trekoon subtask create-many [<task-id>] [--task <task-id>] --subtask <spec> [--subtask <spec> ...]",
  "  --subtask <temp-key>|<title>|<description>|<status>",
  "  Positional <task-id> and --task may be combined only when equal.",
  "  Rejects extra positional arguments and empty required fields.",
  "  Repeated --subtask flags are applied in the order provided.",
  "  Escapes inside compact specs: \\| for |, \\\\ for \\, \\n, \\r, \\t",
  "",
  "List behavior:",
  "  Defaults:",
  "    - Open statuses only: in_progress, in-progress, todo",
  "    - Limit: 10",
  "  Flags:",
  "    --task <id> | --status <csv> | --limit <n> | --cursor <n> | --all | --view table|compact",
  "  Pagination:",
  "    - --cursor is offset-like",
  "    - Machine modes expose meta.pagination.hasMore / nextCursor",
  "  Constraints:",
  "    - --all is mutually exclusive with --status, --limit, and --cursor",
  "",
  "Search/Replace behavior:",
  "  search:",
  "    - trekoon subtask search <subtask-id> \"search text\"",
  "    - Options: --fields title|description|title,description, --preview",
  "    - Scope: subtask title/description only",
  "  replace:",
  "    - trekoon subtask replace <subtask-id> --search \"text\" --replace \"text\"",
  "    - Preview is default; use --apply to mutate",
  "    - --preview and --apply are mutually exclusive",
  "",
  "Update behavior:",
  "  Repo-wide bulk mode:",
  "    trekoon subtask update --all --append <text> [--status <status>]",
  "    trekoon subtask update --ids <csv> --append <text> [--status <status>]",
  "    - preserves existing per-row bulk behavior; not one atomic multi-row update",
  "  Positional-id cascade syntax:",
  "    trekoon subtask update <subtask-id> --all --status done|todo",
  "    - accepted for contract consistency",
  "    - behaves like a normal single-subtask status update",
  "    - positional id + --all supports only --status done|todo",
  "    - do not combine positional id + --all with --ids, --append, --description, or --title",
].join("\n");

const DEP_HELP = [
  "Usage: trekoon dep <add|add-many|remove|list|reverse> [options]",
  "",
  "Subcommands:",
  "  add <source-id> <depends-on-id>",
  "      Create dependency edge: source depends on depends-on.",
  "  add-many --dep <source-ref>|<depends-on-ref> [--dep <spec> ...]",
  "      Create validated dependency edges from compact specs in order.",
  "      Standalone add-many resolves persisted ids only; @<temp-key>",
  "      refs are reserved for higher-level compact batch workflows.",
  "  remove <source-id> <depends-on-id>",
  "      Remove one dependency edge if it exists.",
  "  list <source-id>",
  "      Show direct dependencies for a node.",
  "  reverse <target-id>",
  "      Show downstream nodes blocked by target (with distance).",
  "",
  "Examples:",
  "  trekoon dep add <task-a> <task-b>",
  "  trekoon dep remove <task-a> <task-b>",
  "  trekoon dep list <task-a>",
  "  trekoon dep reverse <task-b>",
].join("\n");

const EVENTS_HELP = [
  "Usage: trekoon events prune [--dry-run] [--archive] [--retention-days <n>]",
  "",
  "Purpose:",
  "  Manage retention for internal sync event log rows.",
  "",
  "Options:",
  "  --dry-run             Preview candidate/archive/delete counts only.",
  "  --archive             Copy pruned rows to event_archive before delete.",
  "  --retention-days <n>  Keep last n days (positive integer, default 90).",
  "",
  "Examples:",
  "  trekoon events prune --dry-run",
  "  trekoon events prune --retention-days 30",
  "  trekoon events prune --archive",
].join("\n");

const MIGRATE_HELP = [
  "Usage: trekoon migrate <status|rollback> [--to-version <n>]",
  "",
  "Subcommands:",
  "  status",
  "      Show current schema version, latest version, and pending count.",
  "  rollback [--to-version <n>]",
  "      Roll back migrations; default target is one version back.",
  "",
  "Examples:",
  "  trekoon migrate status",
  "  trekoon migrate rollback",
  "  trekoon migrate rollback --to-version 1",
].join("\n");

const SYNC_HELP = [
  "Usage: trekoon sync <status|pull|resolve|conflicts> [options]",
  "",
  "Subcommands:",
  "  status [--from <branch>]",
  "      Show ahead/behind counts and pending conflicts vs source branch (default: main).",
  "  pull --from <branch>",
  "      Pull and apply upstream tracker events from a source branch.",
  "  conflicts list [--mode pending|all]",
  "      List sync conflicts (default mode: pending).",
  "  conflicts show <conflict-id>",
  "      Show full details for one conflict.",
  "  resolve <conflict-id> --use ours|theirs",
  "      Resolve a pending conflict by selecting ours or theirs.",
  "",
  "Compatibility mode:",
  "  --compat legacy-sync-command-ids",
  "      Emits legacy sync command IDs (sync_status, sync_pull, ...)",
  "      in machine output only and includes deprecation metadata.",
  "      Migration: remove --compat and consume dotted IDs (sync.status).",
  "      Planned compatibility window closes after 2026-09-30.",
  "",
  "Examples:",
  "  trekoon sync status",
  "  trekoon sync status --from main",
  "  trekoon sync pull --from main",
  "  trekoon sync conflicts list",
  "  trekoon sync conflicts list --mode all",
  "  trekoon sync conflicts show <conflict-id>",
  "  trekoon sync resolve <conflict-id> --use ours",
].join("\n");

const SESSION_HELP = [
  "Usage: trekoon session [--json|--toon]",
  "",
  "Purpose:",
  "  One-call agent orientation. Opens DB once and returns:",
  "    - diagnostics: storageMode, recoveryRequired, recoveryStatus",
  "    - sync: ahead/behind counts and pendingConflicts vs main",
  "    - next: full task tree with subtasks for the top ready candidate (null if none)",
  "    - nextDeps: blocker list with statuses for the next task (empty if none)",
  "    - readiness: readyCount and blockedCount across all open tasks",
  "",
  "Output modes:",
  "  human  Multi-section summary (default in TTY)",
  "  toon   Compact pipe-encoded envelope",
  "  json   Full structured JSON envelope",
  "",
  "Examples:",
  "  trekoon session",
  "  trekoon --toon session",
  "  trekoon --json session",
].join("\n");

const SKILLS_HELP = [
  "Usage:",
  "  trekoon skills install [--link --editor opencode|claude|pi] [--to <path>] [--allow-outside-repo]",
  "  trekoon skills update",
  "",
  "Purpose:",
  "  Install or refresh the project-local Trekoon skill asset.",
  "",
  "Install behavior:",
  "  - Always installs canonical file to:",
  "      <cwd>/.agents/skills/trekoon/SKILL.md",
  "  - Use --link to also create an editor symlink named 'trekoon'.",
  "  - --editor is required when --link is used (opencode|claude|pi).",
  "  - --to overrides the symlink root for --link only.",
  "  - Without --allow-outside-repo, link targets must resolve inside repo.",
  "  - --allow-outside-repo requires --link and disables that boundary check.",
  "",
  "Update behavior:",
  "  - Refreshes canonical SKILL file in the install path above.",
  "  - Auto-creates or refreshes editor symlinks when editor config dir exists.",
  "  - Skips editors with no config dir or conflicting paths.",
  "",
  "Examples:",
  "  trekoon skills install",
  "  trekoon skills install --link --editor opencode",
  "  trekoon skills install --link --editor claude --to .claude/skills",
  "  trekoon skills install --link --editor pi --to ../shared/skills --allow-outside-repo",
  "  trekoon skills update",
].join("\n");

const COMMAND_HELP: Record<string, string> = {
  init: INIT_HELP,
  board: BOARD_HELP,
  quickstart: QUICKSTART_HELP,
  session: SESSION_HELP,
  wipe: WIPE_HELP,
  epic: EPIC_HELP,
  task: TASK_HELP,
  subtask: SUBTASK_HELP,
  dep: DEP_HELP,
  events: EVENTS_HELP,
  migrate: MIGRATE_HELP,
  sync: SYNC_HELP,
  skills: SKILLS_HELP,
  help: "Usage: trekoon help [command] [--json|--toon]",
};

export function resolveHelpText(topic: string | null): string {
  if (!topic) {
    return ROOT_HELP;
  }

  return COMMAND_HELP[topic] ?? `Unknown command for help: ${topic}`;
}

export async function runHelp(context: CliContext): Promise<CliResult> {
  const topic: string | null = context.args[0] ?? null;
  const text: string = resolveHelpText(topic);

  return okResult({
    command: "help",
    human: text,
    data: {
      topic,
      text,
      version: CLI_VERSION,
    },
  });
}
