import { okResult } from "../io/output";
import { type CliContext, type CliResult } from "../runtime/command-types";

const QUICKSTART_TEXT = [
  "Trekoon quickstart",
  "",
  "Agents: always use --toon on every command.",
  "Aligned with: .agents/skills/trekoon/SKILL.md",
  "",
  "1) Storage model",
  "  In git repos and worktrees, Trekoon keeps one shared .trekoon directory",
  "  and one shared .trekoon/trekoon.db database per repository.",
  "  Keep .trekoon gitignored. The DB is live state, not source code.",
  "  Don't commit the DB; that snapshots machine-local state and won't help.",
  "",
  "2) Agent startup",
  "  Single call: trekoon --toon session",
  "  Returns diagnostics, sync status, next ready task, its dependencies,",
  "  and the full task payload. Replaces init + sync status + task next in one call.",
  "",
  "  If diagnostics show recoveryRequired or a tracked/ignored mismatch,",
  "  stop and fix the setup before continuing.",
  "",
  "  Manual bootstrap (step by step):",
  "    trekoon --toon init",
  "    trekoon --toon sync status",
  "    trekoon --toon task next",
  "",
  "3) Execution loop",
  "  1. Start session:  trekoon --toon session [--epic <epic-id>]",
  "  2. Claim work:     trekoon --toon task update <task-id> --status in_progress",
  "  3. Log progress:   trekoon --toon task update <task-id> --append \"Done with implementation\"",
  "  4. Finish:         trekoon --toon task done <task-id>",
  "     Returns the next ready task, its deps, and full payload.",
  "  5. Or report block: trekoon --toon task update <task-id> --append \"Blocked: <reason>\" --status blocked",
  "",
  "4) Orientation and suggestions",
  "  Next-action suggestions:  trekoon --toon suggest [--epic <epic-id>]",
  "  Epic progress:            trekoon --toon epic progress <epic-id>",
  "  Open the board:           trekoon board open",
  "",
  "5) Common commands",
  "  Full epic tree:        trekoon --toon epic show <epic-id> --all",
  "  Full task payload:     trekoon --toon task show <task-id> --all",
  "  Check dependencies:    trekoon --toon dep list <task-id>",
  "  What does this unblock: trekoon --toon dep reverse <task-or-subtask-id>",
  "  Filtered list:         trekoon --toon task list --status in_progress,todo --limit 20",
  "  Paginate:              trekoon --toon task list --cursor <n>",
  "  Bulk update:           trekoon --toon task update --ids id1,id2 --append \"...\" --status in_progress",
  "  Ready queue:           trekoon --toon task ready [--limit <n>] [--epic <id>]",
  "  Next candidate:        trekoon --toon task next [--epic <id>]",
  "",
  "6) List and view defaults",
  "  Default scope: open work (in_progress, todo), limit 10.",
  "  Filters: --status <csv>, --limit <n>, --cursor <n>, or --all for everything.",
  "  Views: --view table (default) or --view compact.",
  "  --all cannot be combined with --status, --limit, or --cursor.",
  "",
  "7) Pre-merge sync",
  "  trekoon --toon sync status",
  "  trekoon --toon sync pull --from main",
  "  trekoon --toon sync conflicts list",
  "  trekoon --toon sync conflicts show <id>",
  "  trekoon --toon sync resolve <id> --use theirs --dry-run",
  "  trekoon --toon sync resolve <id> --use ours|theirs",
  "  trekoon --toon sync resolve --all --use ours          # batch: all pending at once",
  "  trekoon --toon sync status",
  "  Always inspect conflicts before resolving. For uniform conflicts, --all",
  "  resolves every pending conflict in one command. Optional --entity <id>",
  "  and --field <name> narrow the batch. In human mode, --use theirs prompts",
  "  for both single-conflict and batch resolve. Single-conflict prompts show",
  "  field/value details; batch prompts use a count-only confirmation (30s",
  "  timeout, defaults to reject).",
  "",
  "8) Wipe (destructive recovery only)",
  "  trekoon wipe --yes",
  "  Removes the shared .trekoon directory for every worktree in the repo.",
  "  Don't use this for routine cleanup, sync fixes, or gitignore issues.",
].join("\n");

export async function runQuickstart(_: CliContext): Promise<CliResult> {
  return okResult({
    command: "quickstart",
    human: QUICKSTART_TEXT,
    data: {
      localModel: {
        storageDir: ".trekoon",
        databaseFile: ".trekoon/trekoon.db",
        storageScope: "repo-shared-across-worktrees",
        gitPolicy: "gitignored-operational-state",
        mergeBehavior: "manual-sync",
      },
      alignedSkill: ".agents/skills/trekoon/SKILL.md",
      requiresToonForAgents: true,
      bootstrapChecklist: [
        "trekoon --toon session",
        "Replaces: init + sync status + task next + dep list + task show in one call",
        "Fail fast on recoveryRequired or tracked/ignored mismatch diagnostics",
        "Confirm meta.storageRootDiagnostics.sharedStorageRoot matches the repo root",
      ],
      bootstrapLegacy: [
        "trekoon --toon init",
        "trekoon --toon sync status",
        "trekoon --toon task next",
        "trekoon --toon dep list <task-id>",
        "trekoon --toon task show <task-id> --all",
      ],
      preMergeFlow: [
        "trekoon --toon sync status",
        "trekoon --toon sync pull --from main",
        "trekoon --toon sync conflicts list",
        "trekoon --toon sync conflicts show <id>",
        "trekoon --toon sync resolve <id> --use theirs --dry-run",
        "trekoon --toon sync resolve <id> --use ours|theirs",
        "trekoon --toon sync resolve --all --use ours",
        "trekoon --toon sync status",
      ],
      executionLoop: [
        "trekoon --toon session",
        "trekoon --toon task update <task-id> --status in_progress",
        "trekoon --toon task update <task-id> --append \"Completed implementation\"",
        "trekoon --toon task done <task-id>",
      ],
      diagnostics: [
        "storageMode",
        "repoCommonDir",
        "worktreeRoot",
        "sharedStorageRoot",
        "databaseFile",
        "recoveryRequired",
      ],
      recoveryGuidance: [
        "Run trekoon --toon init to bootstrap or re-bootstrap shared storage",
        "Stop when diagnostics report tracked/ignored mismatch or ambiguous recovery",
        "Do not commit .trekoon/trekoon.db; remove the tracked DB and keep .trekoon ignored",
      ],
      powerUserCommands: [
        "trekoon --toon epic show <epic-id> --all",
        "trekoon --toon task show <task-id> --all",
        "trekoon --toon dep list <task-id>",
        "trekoon --toon dep reverse <task-or-subtask-id>",
        "trekoon --toon task list --status in_progress,todo --limit 20",
        "trekoon --toon task list --cursor <n>",
        "trekoon --toon task update --ids id1,id2 --append \"...\" --status in_progress",
      ],
      machineExamples: [
        "trekoon --toon quickstart",
        "trekoon --toon session",
        "trekoon --toon session --epic <epic-id>",
        "trekoon --toon suggest",
        "trekoon --toon epic progress <epic-id>",
        "trekoon --toon task done <task-id>",
        "trekoon --toon task show <task-id> --all",
        "trekoon --toon epic show <epic-id> --all",
        "trekoon --toon sync status",
        "trekoon --toon task ready --limit 5",
        "trekoon --toon task next",
        "trekoon --toon dep reverse <task-or-subtask-id>",
      ],
      wipeWarning: {
        command: "trekoon wipe --yes",
        scope: "repo-wide shared storage",
        destructive: true,
      },
    },
  });
}
