import { okResult } from "../io/output";
import { type CliContext, type CliResult } from "../runtime/command-types";

const QUICKSTART_TEXT = [
  "Trekoon quickstart",
  "",
  "This quickstart is aligned with .agents/skills/trekoon/SKILL.md.",
  "For agents: always use --toon for every command.",
  "",
  "1) Shared storage model",
  "- In git repos and worktrees, Trekoon resolves one repo-scoped .trekoon directory.",
  "- Every worktree for the same repo points at the same .trekoon/trekoon.db file.",
  "- Keep .trekoon gitignored: the SQLite DB is live operational state, not source.",
  "- Committing the DB is the wrong fix for setup drift because it snapshots machine-local state.",
  "",
  "2) Bootstrap and agent startup (primary)",
  "- Single call: trekoon --toon session",
  "- Replaces: init + sync status + task next + dep list + task show in one call.",
  "- Returns diagnostics, next ready task, its dependencies, and full task payload.",
  "- If diagnostics show recoveryRequired or a tracked/ignored mismatch, stop and repair setup.",
  "- Do not continue after storage mismatch, ambiguous recovery, or broken bootstrap warnings.",
  "- In worktrees, confirm meta.storageRootDiagnostics.sharedStorageRoot matches the repo root.",
  "",
  "2a) Bootstrap (manual/legacy — use session instead)",
  "- 1. Initialize or verify shared storage: trekoon --toon init",
  "- 2. Read machine diagnostics: trekoon --toon sync status",
  "- 3. Select next task: trekoon --toon task next",
  "- 4. Check dependencies: trekoon --toon dep list <task-id>",
  "- 5. Show full task: trekoon --toon task show <task-id> --all",
  "",
  "3) AI execution loop (deterministic, dependency-aware)",
  "- 1. Start or resume session: trekoon --toon session",
  "- 2. Claim work: trekoon --toon task update <task-id> --status in_progress",
  "- 3. Complete with context: trekoon --toon task done <task-id> --append \"Completed implementation\"",
  "  - Replaces: update status done + task next + dep list + task show in one call.",
  "  - Returns next ready task, its dependencies, and full task payload.",
  "- 4. Or report block: trekoon --toon task update <task-id> --append \"Blocked by <reason>\" --status blocked",
  "",
  "4) Worktree diagnostics and recovery",
  "- Read machine fields when available: storageMode, repoCommonDir, worktreeRoot, sharedStorageRoot, databaseFile.",
  "- sharedStorageRoot differs from worktreeRoot in linked worktrees; that is expected and should be visible.",
  "- If recoveryRequired is true, run trekoon --toon init and follow the reported recovery action before more commands.",
  "- If tracked and ignored storage disagree, delete the bad fix in Git and re-bootstrap local storage instead.",
  "",
  "5) Power-user command patterns (aligned with skill)",
  "- Inspect full epic tree: trekoon --toon epic show <epic-id> --all",
  "- Inspect full task payload: trekoon --toon task show <task-id> --all",
  "- Check direct dependencies before starting: trekoon --toon dep list <task-id>",
  "- Find what this item unblocks: trekoon --toon dep reverse <task-or-subtask-id>",
  "- Filter list explicitly: trekoon --toon task list --status in_progress,todo --limit 20",
  "- Paginate deterministically: trekoon --toon task list --cursor <n>",
  "- Bulk append/status update: trekoon --toon task update --ids id1,id2 --append \"...\" --status in_progress",
  "",
  "6) Task details and description",
  "- Human list and show views default to table format.",
  "- Alternate list view: add --view compact.",
  "- task/epic/subtask list defaults: open work only (in_progress/in-progress, todo), max 10.",
  "- Filter list by status: --status in_progress,todo (CSV).",
  "- Change page size: --limit <n>. Show all statuses and all rows with --all.",
  "- Continue pagination with --cursor <n> (offset-like list position).",
  "- --all cannot be combined with --status, --limit, or --cursor.",
  "- Bulk update: use --all or --ids <csv> with --append and/or --status.",
  "- Bulk update rejects positional id, and --all/--ids cannot be combined.",
  "- Ready queue: trekoon task ready [--limit <n>] [--epic <id>] (deterministic order).",
  "- Next execution candidate: trekoon task next [--epic <id>]",
  "- Full tree + descriptions (canonical): trekoon --toon epic show <epic-id> --all",
  "- Full task payload (including description): trekoon --toon task show <task-id> --all",
  "- Optional integration format: trekoon --json task show <task-id> --all",
  "",
  "7) Pre-merge sync flow",
  "- Run: trekoon --toon sync status",
  "- Pull upstream tracker events: trekoon --toon sync pull --from main",
  "- Inspect conflicts before resolving:",
  "  1. trekoon --toon sync conflicts list",
  "  2. trekoon --toon sync conflicts show <id>",
  "  3. trekoon --toon sync resolve <id> --use ours|theirs",
  "- Run sync status again before opening or merging a PR.",
  "",
  "8) Shared-storage wipe warning",
  "- trekoon wipe --yes removes the shared repo-scoped .trekoon directory for every worktree in the repo.",
  "- Treat wipe as destructive recovery, not routine cleanup.",
  "- Never use wipe as a substitute for sync, bootstrap, or gitignore fixes.",
  "",
  "9) Machine output examples",
  "- trekoon --toon quickstart",
  "- trekoon --toon session",
  "- trekoon --toon task done <task-id> --append \"Completed implementation\"",
  "- trekoon --toon task show <task-id> --all",
  "- trekoon --toon epic show <epic-id> --all",
  "- trekoon --toon sync status",
  "- trekoon --toon task ready --limit 5",
  "- trekoon --toon task next",
  "- trekoon --toon dep reverse <task-or-subtask-id>",
].join("\n");

export async function runQuickstart(_: CliContext): Promise<CliResult> {
  return okResult({
    command: "quickstart",
    human: QUICKSTART_TEXT,
    data: {
      localModel: {
        storageDir: ".trekoon",
        databaseFile: ".trekoon/trekoon.db",
        storageScope: "repo-shared-across-worktrees",
        gitPolicy: "gitignored-operational-state",
        mergeBehavior: "manual-sync",
      },
      alignedSkill: ".agents/skills/trekoon/SKILL.md",
      requiresToonForAgents: true,
      bootstrapChecklist: [
        "trekoon --toon session",
        "Replaces: init + sync status + task next + dep list + task show in one call",
        "Fail fast on recoveryRequired or tracked/ignored mismatch diagnostics",
        "Confirm meta.storageRootDiagnostics.sharedStorageRoot matches the repo root",
      ],
      bootstrapLegacy: [
        "trekoon --toon init",
        "trekoon --toon sync status",
        "trekoon --toon task next",
        "trekoon --toon dep list <task-id>",
        "trekoon --toon task show <task-id> --all",
      ],
      preMergeFlow: [
        "trekoon --toon sync status",
        "trekoon --toon sync pull --from main",
        "trekoon --toon sync conflicts list",
        "trekoon --toon sync conflicts show <id>",
        "trekoon --toon sync resolve <id> --use ours|theirs",
        "trekoon --toon sync status",
      ],
      executionLoop: [
        "trekoon --toon session",
        "trekoon --toon task update <task-id> --status in_progress",
        "trekoon --toon task done <task-id> --append \"Completed implementation\"",
      ],
      diagnostics: [
        "storageMode",
        "repoCommonDir",
        "worktreeRoot",
        "sharedStorageRoot",
        "databaseFile",
        "recoveryRequired",
      ],
      recoveryGuidance: [
        "Run trekoon --toon init to bootstrap or re-bootstrap shared storage",
        "Stop when diagnostics report tracked/ignored mismatch or ambiguous recovery",
        "Do not commit .trekoon/trekoon.db; remove the tracked DB and keep .trekoon ignored",
      ],
      powerUserCommands: [
        "trekoon --toon epic show <epic-id> --all",
        "trekoon --toon task show <task-id> --all",
        "trekoon --toon dep list <task-id>",
        "trekoon --toon dep reverse <task-or-subtask-id>",
        "trekoon --toon task list --status in_progress,todo --limit 20",
        "trekoon --toon task list --cursor <n>",
        "trekoon --toon task update --ids id1,id2 --append \"...\" --status in_progress",
      ],
      machineExamples: [
        "trekoon --toon quickstart",
        "trekoon --toon session",
        "trekoon --toon task done <task-id> --append \"Completed implementation\"",
        "trekoon --toon task show <task-id> --all",
        "trekoon --toon epic show <epic-id> --all",
        "trekoon --toon sync status",
        "trekoon --toon task ready --limit 5",
        "trekoon --toon task next",
        "trekoon --toon dep reverse <task-or-subtask-id>",
      ],
      wipeWarning: {
        command: "trekoon wipe --yes",
        scope: "repo-wide shared storage",
        destructive: true,
      },
    },
  });
}
