import { okResult } from "../io/output";
import { type CliContext, type CliResult } from "../runtime/command-types";

const QUICKSTART_TEXT = [
  "Trekoon quickstart",
  "",
  "This quickstart is aligned with .agents/skills/trekoon/SKILL.md.",
  "For agents: always use --toon for every command.",
  "",
  "1) Local DB and worktree model",
  "- Every worktree stores tracker state at .trekoon/trekoon.db.",
  "- This DB stays local; it is not merged by Git automatically.",
  "",
  "2) Agent session-start checklist (verify setup + current state)",
  "- 1. Verify tracker exists (or initialize once): trekoon --toon init",
  "- 2. Check sync baseline: trekoon --toon sync status",
  "- 3. Load active context: trekoon --toon epic list",
  "- 4. Load active tasks: trekoon --toon task list",
  "- 5. Load deterministic candidates: trekoon --toon task ready --limit 5",
  "- 6. If blocked, inspect downstream impact: trekoon --toon dep reverse <task-or-subtask-id>",
  "",
  "3) AI execution loop (deterministic, dependency-aware)",
  "- 1. Sync branch/worktree state: trekoon --toon sync status",
  "- 2. Select ready work: trekoon --toon task ready --limit 5",
  "- 3. Pick top candidate when needed: trekoon --toon task next",
  "- 4. Check downstream blockers: trekoon --toon dep reverse <task-or-subtask-id>",
  "- 5. Claim work and update status: trekoon --toon task update <task-id> --status in_progress",
  "- 6. Complete with context: trekoon --toon task update <task-id> --append \"Completed implementation\" --status done",
  "- 7. Or report block: trekoon --toon task update <task-id> --append \"Blocked by <reason>\" --status blocked",
  "",
  "4) Power-user command patterns (aligned with skill)",
  "- Inspect full epic tree: trekoon --toon epic show <epic-id> --all",
  "- Inspect full task payload: trekoon --toon task show <task-id> --all",
  "- Check direct dependencies before starting: trekoon --toon dep list <task-id>",
  "- Find what this item unblocks: trekoon --toon dep reverse <task-or-subtask-id>",
  "- Filter list explicitly: trekoon --toon task list --status in_progress,todo --limit 20",
  "- Paginate deterministically: trekoon --toon task list --cursor <n>",
  "- Bulk append/status update: trekoon --toon task update --ids id1,id2 --append \"...\" --status in_progress",
  "",
  "5) Task details and description",
  "- Human list and show views default to table format.",
  "- Alternate list view: add --view compact.",
  "- task/epic/subtask list defaults: open work only (in_progress/in-progress, todo), max 10.",
  "- Filter list by status: --status in_progress,todo (CSV).",
  "- Change page size: --limit <n>. Show all statuses and all rows with --all.",
  "- Continue pagination with --cursor <n> (offset-like list position).",
  "- --all cannot be combined with --status, --limit, or --cursor.",
  "- Bulk update: use --all or --ids <csv> with --append and/or --status.",
  "- Bulk update rejects positional id, and --all/--ids cannot be combined.",
  "- Ready queue: trekoon task ready [--limit <n>] [--epic <id>] (deterministic order).",
  "- Next execution candidate: trekoon task next [--epic <id>]",
  "- Full tree + descriptions (canonical): trekoon --toon epic show <epic-id> --all",
  "- Full task payload (including description): trekoon --toon task show <task-id> --all",
  "- Optional integration format: trekoon --json task show <task-id> --all",
  "",
  "6) Pre-merge sync flow",
  "- Run: trekoon --toon sync status",
  "- Pull upstream tracker events: trekoon --toon sync pull --from main",
  "- Resolve conflicts if needed: trekoon --toon sync resolve <id> --use ours",
  "- Run sync status again before opening or merging a PR.",
  "",
  "7) Machine output examples",
  "- trekoon --toon quickstart",
  "- trekoon --toon task show <task-id> --all",
  "- trekoon --toon epic show <epic-id> --all",
  "- trekoon --toon sync status",
  "- trekoon --toon task ready --limit 5",
  "- trekoon --toon task next",
  "- trekoon --toon dep reverse <task-or-subtask-id>",
].join("\n");

export async function runQuickstart(_: CliContext): Promise<CliResult> {
  return okResult({
    command: "quickstart",
    human: QUICKSTART_TEXT,
    data: {
      localModel: {
        storageDir: ".trekoon",
        databaseFile: ".trekoon/trekoon.db",
        mergeBehavior: "manual-sync",
      },
      alignedSkill: ".agents/skills/trekoon/SKILL.md",
      requiresToonForAgents: true,
      agentStartupChecklist: [
        "trekoon --toon init",
        "trekoon --toon sync status",
        "trekoon --toon epic list",
        "trekoon --toon task list",
        "trekoon --toon task ready --limit 5",
        "trekoon --toon dep reverse <task-or-subtask-id>",
      ],
      preMergeFlow: [
        "trekoon --toon sync status",
        "trekoon --toon sync pull --from main",
        "trekoon --toon sync resolve <id> --use ours",
        "trekoon --toon sync status",
      ],
      executionLoop: [
        "trekoon --toon sync status",
        "trekoon --toon task ready --limit 5",
        "trekoon --toon task next",
        "trekoon --toon dep reverse <task-or-subtask-id>",
        "trekoon --toon task update <task-id> --status in_progress",
      ],
      powerUserCommands: [
        "trekoon --toon epic show <epic-id> --all",
        "trekoon --toon task show <task-id> --all",
        "trekoon --toon dep list <task-id>",
        "trekoon --toon dep reverse <task-or-subtask-id>",
        "trekoon --toon task list --status in_progress,todo --limit 20",
        "trekoon --toon task list --cursor <n>",
        "trekoon --toon task update --ids id1,id2 --append \"...\" --status in_progress",
      ],
      machineExamples: [
        "trekoon --toon quickstart",
        "trekoon --toon task show <task-id> --all",
        "trekoon --toon epic show <epic-id> --all",
        "trekoon --toon sync status",
        "trekoon --toon task ready --limit 5",
        "trekoon --toon task next",
        "trekoon --toon dep reverse <task-or-subtask-id>",
      ],
    },
  });
}
